-- +goose Up
ALTER TABLE users ADD COLUMN full_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN password TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE users DROP COLUMN full_name;
ALTER TABLE users DROP COLUMN password;
ALTER TABLE users DROP COLUMN created_at;
